# Generated by Django 5.0.6 on 2024-05-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_date_alter_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.TextField(max_length=255),
        ),
    ]
